import logging
import uuid
from pathlib import Path
import chromadb
from chromadb.utils.embedding_functions.onnx_mini_lm_l6_v2 import ONNXMiniLM_L6_V2
from chromadb.config import Settings
import time

from argusAI.utils.event_message_sanitizer import MessageSanitizer

# Basic logging setup
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


class BGE_SMALL(ONNXMiniLM_L6_V2):
    MODEL_NAME = "bge-small-en-v1.5"
    DOWNLOAD_PATH = Path.home() / ".cache" / "chroma" / "onnx_models" / MODEL_NAME
    EXTRACTED_FOLDER_NAME = "onnx"
    ARCHIVE_FILENAME = "onnx.tar.gz"
    MODEL_DOWNLOAD_URL = (
        "https://scylla-qa-public.s3.us-east-1.amazonaws.com/ArgusAI/bge-small-en-v1.5/onnx.tar.gz"
    )
    _MODEL_SHA256 = "e7d1743b0c08f55c687cff6af696683398682f9ab4fb3cad1be644ee5553a72d"


class EmbeddingTester:
    def __init__(self):
        self.client = chromadb.Client(Settings(anonymized_telemetry=False))
        self.collection = self.client.get_or_create_collection("test_embeddings")
        self.embedding_model = BGE_SMALL()
        self.sanitizer = MessageSanitizer()
        logger.info("Embedding Tester initialized")

    def generate_embedding(self, message):
        start_time = time.time()

        # Generate embedding
        embedding = self.embedding_model([message])[0]

        # Store in ChromaDB
        message_id = f"test_{int(start_time * 1000)}"
        self.collection.upsert(
            ids=[message_id],
            embeddings=[embedding],
            metadatas=[{"message": message}]
        )

        end_time = time.time()
        logger.info(f"Embedding generated for '{message}' in {end_time - start_time:.3f} seconds")
        return embedding

    def test_messages(self, messages):
        results = []
        total_start = time.time()
        # messages = [self.sanitizer.sanitize(uuid.uuid4(), event_text) for event_text in messages]
        # embeddings = self.embedding_model(messages)
        for message in messages:
            embedding = self.generate_embedding(message)
            # results.append({
            #     'message': message,
            #     'embedding': embedding,
            #     'length': len(embedding)
            # })

        total_time = time.time() - total_start
        logger.info(f"Processed {len(messages)} messages in {total_time:.3f} seconds")
        return results


if __name__ == "__main__":
    # Example usage
    tester = EmbeddingTester()

    # Test messages
    test_messages = [
        "2025-02-22 CassandraStressLogEvent during_nemesis TerminateAndReplaceNode type OperationOnKey regex Operation x10 on key(s) (dc name eu-west-1) java_io.IOException Operation x10 on keys 364c4f36393031503330 Error executing ReadTimeoutException Cassandra timeout during read query at consistency LOCAL_QUORUM (3 responses were required but only 2 replica responded). In case this was generated during read repair the consistency level is not representative of the actual consistency.",
        "2025-02-22 CassandraStressEvent during_nemesis TerminateAndReplaceNode duration 10h12m59s (dc name eu-west-1) stress_cmd cassandra-stress read cl LOCAL_QUORUM duration 1440m -schema replication(strategy NetworkTopologyStrategy replication_factor 3) compaction(strategy SizeTieredCompactionStrategy) -mode cql3 native -rate threads 40 -pop dist uniform(1..20971520) -col n FIXED5 size FIXED16 -log interval 5 errors Stress command completed with bad status 1 Failed to connect over JMX; not collecting these stats com_datastax.driver_core.exceptions_TransportException 2a05 d018 12e3 f002 9896 e402 5816 e900/2a05 d018 12e3 f002 9896 e402 5816 e900 9042 Connection has been closed",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c3_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DatabaseLogEvent during_nemesis TerminateAndReplaceNode type RUNTIME_ERROR regex std runtime_error node db db !ERR scylla 5597 shard 4 gms storage_proxy - exception during mutation write to 3847d051-a3e2-4dd2-a67e-ce21edf48718 utils internal nested_exception<std runtime_error> (Could not write mutation keyspace1 sec_ind_c2_index ( pk to commitlog) seastar gate_closed_exception (gate closed)",
        "2025-02-22 DisruptionEvent duration 29m37s nemesis_name TerminateAndReplaceNode (dc name eu-westscylla_node_west) errors Killed by tearDown - test fail TB in wrapper result method(*args 1 **kwargs) in disrupt_terminate_and_replace_node self__terminate_and_replace_node() in _terminate_and_replace_node new_node self_replace_node(old_node_ip host_id rack self_target_node.rack in wrapped res func(*args **kwargs) in replace_node return self__replace_cluster_node(old_node_ip host_id rack rack is_zero_node is_zero_node) in _replace_cluster_node self_cluster.wait_for_init(node_list new_node timeout timeout check_node_health False) in wrapper verify_node_setup_or_startup(start_time startup_queue startup_results) in verify_node_setup_or_startup lenresults lennode_list strnode inttime_elapsed) in __str__ self__dc_info_str()) in _dc_info_str elif len(self_parent_cluster.params_region_names) > 1 and self_datacenter in datacenter datacenter_name_per_region self_parent_cluster.get_datacenter_name_per_region(db_nodes self ) in get_datacenter_name_per_region if status nodes 0 .get_nodes_status() in get_nodes_status statuses self_parent_cluster.get_nodetool_status(verification_node self) in inner return func(*args **kwargs) in get_nodetool_status res verification_node_run_nodetool(status publish_event False) in run_nodetool runner(cmd timeout timeout ignore_status ignore_status verbose verbose retry retry) in run result _run() in inner return func(*args **kwargs) in _run return self__run_execute(cmd timeout ignore_status verbose new_session watchers) in _run_execute result connection_run(**command_kwargs) in run channel self_open_channel() in open_channel sleepdelay sdcm_exceptions.KillNemesis",
        "2025-02-22 TestFrameworkEvent source LongevityTest_test_custom_time longevity_test_LongevityTest)() TB in test_custom_time self_verify_stress_thread(cs_thread_pool stress) in verify_stress_thread results errors cs_thread_pool_verify_results() in verify_results results super().get_results() in get_results for future in concurrent_futures.as_completed(self_results_futures timeout timeout) in as_completed waiter_event.waitwait_timeout in wait signaled self__cond.waittimeout in wait gotit waiter_acquire(True timeout) in critical_failure_handler raise CriticalTestFailure(Critical Error has failed the test) # pylint disable raise-missing-from sdcm_tester.CriticalTestFailure Critical Error has failed the test",
    ]

    results = tester.test_messages(test_messages)

    # Print results
    for result in results:
        logger.info(f"Message: {result['message']}")
        logger.info(f"Embedding length: {result['length']}")
        logger.info(f"First few values: {result['embedding'][:5]}\n")
